### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement cloud-init==22.4.2 (from versions: none) ERROR: No matching distribution found for cloud-init==22.4.2

### ISSUE THREAD

**Issue by ajay-kumar202** [yubint/darazscrape-api#1]
ERROR: Could not find a version that satisfies the requirement cloud-init==22.4.2 (from versions: none)
ERROR: No matching distribution found for cloud-init==22.4.2

**Comment by yubint** [comment]
Issue resolved. Changed the requirements.txt
